- name: Set up webserver
  hosts: webservers
  roles:
    - common
    - firewalld
      #- docker
    - golang

- name: Set up databases
  hosts: dbs
  roles:
    - common
    - backup
    - postgresql
    - elasticsearch
