memqcache_oiddir: '/var/log/pgpool/oiddir'
# TODO Check the machine has enough RAM
# ~10 GB
memqcache_total_size_byte: 10737418240
# 131 mb
memqcache_maxcache_byte: 131072000
# Has to be bigger or equal to maxcache_byte
memqcache_cache_block_size_byte: 131072000
